name: CI.<%- application_code_kebab %>

on:
    pull_request:
        branches:
            - dev
            - master
        paths:
            - 'apps/<%- application_code_kebab %>/**'

jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: './apps/<%- application_code_kebab %>'

        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: yarn install
            - name: Lint
              run: yarn lint
            - name: Test
              run: yarn test
            - name: Build
              run: yarn run build
