apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gannochenko/<%- composition_code %>-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: 3000
            - name: AUTH0_DOMAIN
              value: gannochenko.eu
            - name: AUTH0_AUDIENCE
              value: https://<%- composition_code %>.app
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
