name: CI

on:
    pull_request:
        branches:
            - dev
            - master
#        paths:
#            - 'packages/example/**'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install
              run: yarn install
#              env:
#                  GITHUB_TOKEN_EXAMPLE_ENVVAR: ${{ secrets.CICD_TOKEN }}
            - name: Install peers
              run: yarn run install-peers
            - name: Lint
              run: yarn run lint
            - name: Test
              run: yarn run test
<% if (is_ui) { %>
            - name: Test visual (install)
              working-directory: ./visual
              run: yarn install
            - name: Test visual
              run: yarn test:visual:cicd
<% } %>
            - name: Build
              run: yarn run build

