name: CD.<%- application_code_kebab %>.#FUNCTION_NAME#

on:
  push:
    branches:
      - master
    paths:
      - 'apps/<%- application_code_kebab %>/src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install node_modules
        run: yarn
        working-directory: ./apps/<%- application_code_kebab %>/

      - name: Build and Deploy
        run: ./script/deploy.sh #FUNCTION_NAME#
        working-directory: ./apps/<%- application_code_kebab %>/
        env:
          SENDIN_BLUE_API_KEY: ${{ secrets.SENDIN_BLUE_API_KEY }}
